name: Scheduled Execution

on:
  schedule:
    - cron: "0 8 * * MON"

jobs:

  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Make
      run: sudo apt-get install make

    - name: Run project
      run: make run
      env:
        RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
